name: Unittests

# Allow to trigger the workflow manually (e.g. when deps changes)
on: [push, workflow_dispatch]

jobs:
  pytest-job:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      # Checkout fusion-surrogates
      - uses: actions/checkout@v4

      # Checkout tglfnn-ukaea
      # lfs: true is needed to pull the model weights
      - uses: actions/checkout@v4
        with:
          repository: "ukaea/tglfnn-ukaea"
          path: "external_dependencies/tglfnn-ukaea"
          lfs: "true"

      # Install deps
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip --version
      - run: pip install -e .[testing]
      - run: pip freeze

      # Run tests (in parallel)
      - name: Run core tests
        run: pytest -vv -n auto

      - name: Test tglfnn-ukaea loading
        run: >-
          TGLFNN_UKAEA_DIR=external_dependencies/tglfnn-ukaea
          pytest -vv fusion_surrogates/tglfnn_ukaea/tglfnn_ukaea_model_test.py
